// 단서와 자물쇠에 쓰는 작은 그림(아이콘)입니다. (x, y)를 가운데로, s를 반지름처럼 써서 그립니다.
// 얼굴이나 표정은 넣지 않고, 한 가지 색과 얇은 어두운 선만 씁니다.
import { R, C, E, P, L, poly } from './escape-props.js?v=escape-10';

const n = v => Math.round(v * 10) / 10;
const EDGE = 'stroke="#1b1712" stroke-width="1.5"';
const M = (pts, f, e = EDGE) => poly(pts.map(([a, b]) => [n(a), n(b)]), f, e);

export const ICONS = {
  bottle: (x, y, s, f) => R(n(x - s * .18), n(y - s), n(s * .36), n(s * .4), '#5a442c') + P(`M${n(x - s * .2)} ${n(y - s * .62)}H${n(x + s * .2)}Q${n(x + s * .5)} ${n(y - s * .4)} ${n(x + s * .5)} ${n(y - s * .05)}V${n(y + s)}H${n(x - s * .5)}V${n(y - s * .05)}Q${n(x - s * .5)} ${n(y - s * .4)} ${n(x - s * .2)} ${n(y - s * .62)}Z`, f, EDGE),
  book: (x, y, s, f) => R(n(x - s * .38), n(y - s), n(s * .76), n(s * 2), f, `rx="${n(s * .08)}" ${EDGE}`) + L(x - s * .38, y - s * .6, x + s * .38, y - s * .6, '#1b1712', 1.5, 'opacity=".6"') + L(x - s * .38, y + s * .6, x + s * .38, y + s * .6, '#1b1712', 1.5, 'opacity=".6"'),
  cup: (x, y, s, f) => P(`M${n(x - s * .7)} ${n(y - s * .6)}H${n(x + s * .5)}L${n(x + s * .38)} ${n(y + s * .8)}H${n(x - s * .58)}Z`, f, EDGE) + P(`M${n(x + s * .45)} ${n(y - s * .3)}q${n(s * .5)} 0 ${n(s * .38)} ${n(s * .5)}q-${n(s * .1)} ${n(s * .3)} -${n(s * .45)} ${n(s * .25)}`, 'none', `stroke="${f}" stroke-width="${n(s * .16)}"`) + E(x - s * .1, y + s * .9, s * .8, s * .14, '#1b1712', 'opacity=".5"'),
  fish: (x, y, s, f) => P(`M${n(x - s * .9)} ${n(y)}Q${n(x - s * .1)} ${n(y - s * .7)} ${n(x + s * .55)} ${n(y)}Q${n(x - s * .1)} ${n(y + s * .7)} ${n(x - s * .9)} ${n(y)}Z`, f, EDGE) + M([[x + s * .45, y], [x + s, y - s * .5], [x + s, y + s * .5]], f),
  candle: (x, y, s, f) => R(n(x - s * .28), n(y - s * .45), n(s * .56), n(s * 1.45), f, EDGE) + P(`M${n(x)} ${n(y - s)}Q${n(x + s * .25)} ${n(y - s * .7)} ${n(x)} ${n(y - s * .5)}Q${n(x - s * .2)} ${n(y - s * .7)} ${n(x)} ${n(y - s)}Z`, '#e5bd71'),
  gem: (x, y, s, f) => M([[x - s * .6, y - s * .45], [x - s * .3, y - s * .8], [x + s * .3, y - s * .8], [x + s * .6, y - s * .45], [x, y + s * .85]], f) + M([[x - s * .3, y - s * .8], [x - s * .1, y - s * .45], [x - s * .6, y - s * .45]], '#fff', 'opacity=".22"'),
  flag: (x, y, s, f) => L(x - s * .55, y - s, x - s * .55, y + s, '#3a3f42', n(s * .14)) + P(`M${n(x - s * .5)} ${n(y - s * .95)}Q${n(x + s * .1)} ${n(y - s * 1.1)} ${n(x + s * .75)} ${n(y - s * .85)}V${n(y - s * .05)}Q${n(x + s * .1)} ${n(y - s * .25)} ${n(x - s * .5)} ${n(y - s * .1)}Z`, f, EDGE),
  apple: (x, y, s, f) => P(`M${n(x)} ${n(y - s * .5)}Q${n(x + s * .9)} ${n(y - s * .9)} ${n(x + s * .75)} ${n(y + s * .2)}Q${n(x + s * .5)} ${n(y + s)} ${n(x)} ${n(y + s * .75)}Q${n(x - s * .5)} ${n(y + s)} ${n(x - s * .75)} ${n(y + s * .2)}Q${n(x - s * .9)} ${n(y - s * .9)} ${n(x)} ${n(y - s * .5)}Z`, f, EDGE) + L(x, y - s * .5, x + s * .15, y - s, '#3a2b1b', 2),
  umbrella: (x, y, s, f) => P(`M${n(x - s)} ${n(y - s * .1)}Q${n(x)} ${n(y - s * 1.3)} ${n(x + s)} ${n(y - s * .1)}Z`, f, EDGE) + P(`M${n(x)} ${n(y - s * .1)}V${n(y + s * .75)}q0 ${n(s * .3)} -${n(s * .3)} ${n(s * .2)}`, 'none', 'stroke="#2a2118" stroke-width="2.4"'),
  lantern: (x, y, s, f) => E(x, y, s * .55, s * .75, f, EDGE) + R(n(x - s * .32), n(y - s * .95), n(s * .64), n(s * .22), '#2a1f15') + R(n(x - s * .32), n(y + s * .72), n(s * .64), n(s * .22), '#2a1f15') + L(x - s * .5, y, x + s * .5, y, '#1b1712', 1, 'opacity=".4"'),
  bird: (x, y, s, f) => P(`M${n(x - s)} ${n(y + s * .15)}L${n(x - s * .48)} ${n(y - s * .12)}Q${n(x - s * .25)} ${n(y - s * .48)} ${n(x + s * .12)} ${n(y - s * .25)}Q${n(x + s * .13)} ${n(y - s * .78)} ${n(x + s * .47)} ${n(y - s * .76)}Q${n(x + s * .75)} ${n(y - s * .73)} ${n(x + s * .73)} ${n(y - s * .44)}L${n(x + s)} ${n(y - s * .35)}L${n(x + s * .65)} ${n(y - s * .17)}Q${n(x + s * .5)} ${n(y + s * .54)} ${n(x - s * .13)} ${n(y + s * .5)}L${n(x - s * .76)} ${n(y + s * .42)}Z`, f, EDGE) + P(`M${n(x - s * .4)} ${n(y - s * .06)}Q${n(x + s * .03)} ${n(y - s * .28)} ${n(x + s * .26)} ${n(y + s * .12)}Q${n(x - s * .04)} ${n(y + s * .42)} ${n(x - s * .4)} ${n(y - s * .06)}`, 'none', 'stroke="#1b1712" stroke-width="1" opacity=".55"') + [-.05, .25].map(k => L(x + s * k, y + s * .44, x + s * k, y + s * .8, f, Math.max(1, s * .07)) + L(x + s * (k - .1), y + s * .8, x + s * (k + .15), y + s * .8, f, Math.max(1, s * .07))).join(''),
  ribbon: (x, y, s, f) => M([[x, y], [x - s, y - s * .6], [x - s, y + s * .6]], f) + M([[x, y], [x + s, y - s * .6], [x + s, y + s * .6]], f) + C(x, y, s * .25, f, EDGE) + M([[x - s * .1, y + s * .1], [x - s * .45, y + s], [x - s * .15, y + s * .9]], f) + M([[x + s * .1, y + s * .1], [x + s * .45, y + s], [x + s * .15, y + s * .9]], f),
  feather: (x, y, s, f) => P(`M${n(x - s * .7)} ${n(y + s)}Q${n(x - s * .4)} ${n(y - s * .3)} ${n(x + s * .7)} ${n(y - s)}Q${n(x + s * .5)} ${n(y + s * .2)} ${n(x - s * .7)} ${n(y + s)}Z`, f, EDGE) + L(x - s * .7, y + s, x + s * .55, y - s * .8, '#1b1712', 1.2, 'opacity=".6"'),
  shell: (x, y, s, f) => P(`M${n(x)} ${n(y + s)}L${n(x - s)} ${n(y - s * .1)}Q${n(x)} ${n(y - s * 1.4)} ${n(x + s)} ${n(y - s * .1)}Z`, f, EDGE) + [-.6, -.2, .2, .6].map(k => L(x, y + s, x + s * k, y - s * .5, '#1b1712', 1, 'opacity=".5"')).join(''),
  mushroom: (x, y, s, f) => P(`M${n(x - s)} ${n(y)}Q${n(x)} ${n(y - s * 1.4)} ${n(x + s)} ${n(y)}Z`, f, EDGE) + R(n(x - s * .22), n(y), n(s * .44), n(s * .9), '#d9cfb3', EDGE),
  bell: (x, y, s, f) => P(`M${n(x)} ${n(y - s)}Q${n(x + s * .75)} ${n(y - s * .9)} ${n(x + s * .7)} ${n(y + s * .3)}L${n(x + s * .9)} ${n(y + s * .7)}H${n(x - s * .9)}L${n(x - s * .7)} ${n(y + s * .3)}Q${n(x - s * .75)} ${n(y - s * .9)} ${n(x)} ${n(y - s)}Z`, f, EDGE) + C(x, y + s * .85, s * .18, '#1b1712'),
  anchor: (x, y, s, f) => C(x, y - s * .75, s * .22, 'none', `stroke="${f}" stroke-width="${n(s * .16)}"`) + L(x, y - s * .5, x, y + s * .9, f, n(s * .18)) + L(x - s * .45, y - s * .25, x + s * .45, y - s * .25, f, n(s * .16)) + P(`M${n(x - s * .8)} ${n(y + s * .3)}Q${n(x - s * .6)} ${n(y + s)} ${n(x)} ${n(y + s * .9)}Q${n(x + s * .6)} ${n(y + s)} ${n(x + s * .8)} ${n(y + s * .3)}`, 'none', `stroke="${f}" stroke-width="${n(s * .18)}"`),
  note: (x, y, s, f) => E(x - s * .25, y + s * .6, s * .38, s * .28, f, `transform="rotate(-20 ${n(x - s * .25)} ${n(y + s * .6)})"`) + L(x + s * .1, y + s * .55, x + s * .1, y - s, f, n(s * .14)) + P(`M${n(x + s * .1)} ${n(y - s)}q${n(s * .5)} ${n(s * .2)} ${n(s * .45)} ${n(s * .7)}`, 'none', `stroke="${f}" stroke-width="${n(s * .14)}"`),
  snow: (x, y, s, f) => [0, 60, 120].map(a => { const c = Math.cos((a * Math.PI) / 180), d = Math.sin((a * Math.PI) / 180); return L(x - c * s, y - d * s, x + c * s, y + d * s, f, n(s * .16), 'stroke-linecap="round"'); }).join('') + C(x, y, s * .2, f),
  flame: (x, y, s, f) => P(`M${n(x)} ${n(y - s)}Q${n(x + s * .9)} ${n(y)} ${n(x + s * .5)} ${n(y + s * .7)}Q${n(x)} ${n(y + s * 1.1)} ${n(x - s * .5)} ${n(y + s * .7)}Q${n(x - s * .9)} ${n(y)} ${n(x)} ${n(y - s)}Z`, f, EDGE),
  wave: (x, y, s, f) => [-.35, .35].map(k => P(`M${n(x - s)} ${n(y + s * k)}q${n(s * .5)} -${n(s * .5)} ${n(s)} 0t${n(s)} 0`, 'none', `stroke="${f}" stroke-width="${n(s * .2)}" stroke-linecap="round"`)).join(''),
  tree: (x, y, s, f) => R(n(x - s * .13), n(y + s * .25), n(s * .26), n(s * .75), '#3a2b1b') + M([[x, y - s], [x + s * .46, y - s * .3], [x + s * .22, y - s * .3], [x + s * .68, y + s * .15], [x + s * .35, y + s * .15], [x + s * .9, y + s * .65], [x - s * .9, y + s * .65], [x - s * .35, y + s * .15], [x - s * .68, y + s * .15], [x - s * .22, y - s * .3], [x - s * .46, y - s * .3]], f),
  hand: (x, y, s, f) => P(`M${n(x - s * .9)} ${n(y - s * .3)}H${n(x + s * .9)}Q${n(x + s * 1.05)} ${n(y - s * .15)} ${n(x + s * .9)} ${n(y)}H${n(x)}V${n(y + s * .6)}Q${n(x - s * .5)} ${n(y + s * .75)} ${n(x - s * .9)} ${n(y + s * .4)}Z`, f, EDGE),
  boat: (x, y, s, f) => P(`M${n(x - s)} ${n(y + s * .3)}H${n(x + s)}L${n(x + s * .6)} ${n(y + s * .8)}H${n(x - s * .6)}Z`, f, EDGE) + L(x, y + s * .3, x, y - s, '#3a2b1b', 2) + M([[x + s * .05, y - s * .9], [x + s * .7, y + s * .15], [x + s * .05, y + s * .15]], '#d9cfb3'),
  house: (x, y, s, f) => M([[x - s, y - s * .1], [x, y - s], [x + s, y - s * .1]], f) + R(n(x - s * .75), n(y - s * .1), n(s * 1.5), n(s * 1.05), f, EDGE) + R(n(x - s * .2), n(y + s * .35), n(s * .4), n(s * .6), '#1b1712'),
  hat: (x, y, s, f) => E(x, y + s * .5, s, s * .25, f, EDGE) + R(n(x - s * .55), n(y - s * .7), n(s * 1.1), n(s * 1.2), f, `rx="${n(s * .2)}" ${EDGE}`) + R(n(x - s * .55), n(y + s * .1), n(s * 1.1), n(s * .2), '#1b1712', 'opacity=".5"'),
  foot: (x, y, s, f) => E(x, y + s * .2, s * .38, s * .62, f) + [[-.32, -.62], [-.08, -.78], [.16, -.76], [.36, -.6]].map(([a, b], i) => C(x + s * a, y + s * b, s * (.15 - i * .015), f)).join(''),
  key: (x, y, s, f) => C(x - s * .45, y, s * .4, 'none', `stroke="${f}" stroke-width="${n(s * .2)}"`) + L(x - s * .05, y, x + s * .95, y, f, n(s * .2)) + L(x + s * .65, y, x + s * .65, y + s * .4, f, n(s * .18)) + L(x + s * .9, y, x + s * .9, y + s * .3, f, n(s * .18)),
  coin: (x, y, s, f) => C(x, y, s * .8, f, EDGE) + C(x, y, s * .55, 'none', 'stroke="#1b1712" stroke-width="1" opacity=".5"'),
  pear: (x, y, s, f) => P(`M${n(x)} ${n(y - s * .8)}Q${n(x + s * .4)} ${n(y - s * .6)} ${n(x + s * .35)} ${n(y - s * .1)}Q${n(x + s * .85)} ${n(y + s * .4)} ${n(x + s * .5)} ${n(y + s * .85)}Q${n(x)} ${n(y + s * 1.05)} ${n(x - s * .5)} ${n(y + s * .85)}Q${n(x - s * .85)} ${n(y + s * .4)} ${n(x - s * .35)} ${n(y - s * .1)}Q${n(x - s * .4)} ${n(y - s * .6)} ${n(x)} ${n(y - s * .8)}Z`, f, EDGE) + L(x, y - s * .8, x + s * .1, y - s * 1.1, '#3a2b1b', 2),
  cloud: (x, y, s, f) => E(x, y + s * .2, s, s * .45, f) + C(x - s * .35, y - s * .05, s * .4, f) + C(x + s * .25, y - s * .2, s * .5, f),
  scarf: (x, y, s, f) => P(`M${n(x - s * .8)} ${n(y - s * .6)}Q${n(x)} ${n(y - s * .2)} ${n(x + s * .8)} ${n(y - s * .6)}V${n(y - s * .2)}Q${n(x)} ${n(y + s * .2)} ${n(x - s * .8)} ${n(y - s * .2)}Z`, f, EDGE) + R(n(x + s * .25), n(y - s * .2), n(s * .38), n(s * 1.1), f, EDGE),
  flower: (x, y, s, f) => [0, 72, 144, 216, 288].map(a => { const c = Math.cos(((a - 90) * Math.PI) / 180), d = Math.sin(((a - 90) * Math.PI) / 180); return C(n(x + c * s * .5), n(y + d * s * .5), n(s * .4), f, EDGE); }).join('') + C(x, y, s * .3, '#e2c588', EDGE),
  dot: (x, y, s, f) => C(x, y, s * .38, f),
  dash: (x, y, s, f) => R(n(x - s * .8), n(y - s * .22), n(s * 1.6), n(s * .44), f, `rx="${n(s * .22)}"`),
};
export const ICON_NAMES = Object.keys(ICONS);
export const icon = (name, x, y, s, f) => ICONS[name]?.(x, y, s, f) ?? C(x, y, s * .5, f);
